from __future__ import annotations

from typing import Any, Protocol

from app.models import (
    AlertRecord,
    EventRecord,
    MetricSample,
    OutputRecord,
    PromptRecord,
    RepairRecord,
    RewardRecord,
    RunRecord,
)


class StorageBackend(Protocol):
    def upsert_run(self, run: RunRecord) -> None: ...

    def insert_metric(self, metric: MetricSample) -> None: ...

    def insert_event(self, event: EventRecord) -> None: ...

    def insert_prompt(self, prompt: PromptRecord) -> None: ...

    def insert_output(self, output: OutputRecord) -> None: ...

    def insert_reward(self, reward: RewardRecord) -> None: ...

    def insert_alert(self, alert: AlertRecord) -> None: ...

    def insert_repair(self, repair: RepairRecord) -> None: ...

    def list_runs(self, *, limit: int = 20) -> list[RunRecord]: ...

    def get_run(self, run_id: str) -> RunRecord | None: ...

    def recent_metrics(
        self,
        metric_names: list[str],
        *,
        limit_per_metric: int = 180,
        run_id: str | None = None,
    ) -> list[MetricSample]: ...

    def recent_events(self, *, limit: int = 80, run_id: str | None = None) -> list[EventRecord]: ...

    def recent_alerts(self, *, limit: int = 50) -> list[AlertRecord]: ...

    def recent_repairs(self, *, limit: int = 40) -> list[RepairRecord]: ...

    def recent_prompts_with_outputs(self, *, limit: int = 40) -> list[dict[str, Any]]: ...

    def recent_rewards(self, *, limit: int = 40) -> list[RewardRecord]: ...

    def count(self, table: str) -> int: ...

    def count_open_alerts(self) -> int: ...

    def table_counts(self) -> dict[str, int]: ...
